# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
project 'sparkles'

target 'sparkles' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bluzzle
  pod 'lottie-ios'
  # pod 'lottie-ios', path: '../node_modules/lottie-ios'
  pod 'lottie-react-native', path: '../node_modules/lottie-react-native'
  pod 'React', path: '../node_modules/react-native'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'sparklesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'sparkles-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bluzzle-tvOS

  target 'sparkles-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
